//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailboxUsage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailbox
    {
        public int Id { get; set; }
        public string UMID { get; set; }
        public string ValueID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string UUID { get; set; }
    }
}
