//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailboxUsage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MailboxUsageEntities2 : DbContext
    {
        public MailboxUsageEntities2()
            : base("name=MailboxUsageEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mailbox> Mailboxes { get; set; }
        public virtual DbSet<UsageStatu> UsageStatus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Using> Usings { get; set; }
        public virtual DbSet<MailboxSendA> MailboxSendAs { get; set; }
    
        public virtual ObjectResult<string> GetUserDetails(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserDetails", userIDParameter);
        }
    }
}
