//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailboxUsage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailbox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mailbox()
        {
            this.Usings = new HashSet<Using>();
        }
    
        public string MailboxID { get; set; }
        public string MailboxName { get; set; }
        public string MailboxEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Using> Usings { get; set; }
    }
}
