//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailboxUsage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Using
    {
        public int ID { get; set; }
        public string MailboxID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Mailbox Mailbox { get; set; }
        public virtual UsageStatu UsageStatu { get; set; }
        public virtual User User { get; set; }
    }
}
